// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sskdgkajywqmrasdhzqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNza2Rna2FqeXdxbXJhc2RoenFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzk0ODEsImV4cCI6MjA2NDk1NTQ4MX0.UpRiTythZOPnFhGEpo7JWXhWsdtBOSBYRz5XglfHAJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);